// <auto-generated />
using System;
using App2c2pTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App2c2pTest.Data.Migrations
{
    [DbContext(typeof(App2c2pContext))]
    [Migration("20181010182804_Seed_Data")]
    partial class Seed_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App2c2pTest.Data.Entites.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(19);

                    b.Property<string>("CardDescription");

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("ExpiryDate")
                        .HasMaxLength(6);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new { Id = 1, Card = "4909-2832-8723-8888", CardDescription = "Visa Card Sample", DateCreated = new DateTime(2018, 10, 10, 19, 28, 2, 930, DateTimeKind.Local), ExpiryDate = 81980, IsActive = true, IsDeleted = false },
                        new { Id = 2, Card = "5909-2222-8723-8888", CardDescription = "Master Card Sample", DateCreated = new DateTime(2018, 10, 10, 19, 28, 2, 931, DateTimeKind.Local), ExpiryDate = 81933, IsActive = true, IsDeleted = false },
                        new { Id = 3, Card = "3409-2222-8723-888", CardDescription = "Amex Card Sample", DateCreated = new DateTime(2018, 10, 10, 19, 28, 2, 931, DateTimeKind.Local), ExpiryDate = 81973, IsActive = true, IsDeleted = false },
                        new { Id = 4, Card = "3528-3589-8723-8888", CardDescription = "JCB Card Sample", DateCreated = new DateTime(2018, 10, 10, 19, 28, 2, 931, DateTimeKind.Local), ExpiryDate = 81963, IsActive = true, IsDeleted = false },
                        new { Id = 5, Card = "3709-2222-8723-8888", CardDescription = "Amex Card Sample", DateCreated = new DateTime(2018, 10, 10, 19, 28, 2, 931, DateTimeKind.Local), ExpiryDate = 81963, IsActive = true, IsDeleted = false }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
